spring:
  application:
    name: discovery-service
  management:
    tracing:
      sampling:
        probability: 1.0
  zipkin:
    base-url: http://http://localhost:9411

server:
  port: 8761

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false