server:
  port: 8765

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      server:
        webflux:
          routes:
            - id: book-service
              uri: lb://book-service
              predicates:
                - Path=/book/**
            - id: exchange-service
              uri: lb://exchange-service
              predicates:
                - Path=/exchange/**
  management:
    tracing:
      sampling:
        probability: 1.0
  zipkin:
    base-url: ${SPRING_ZIPKIN_BASEURL:http://localhost:9411}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_CLIENT_SERVICEURL_DEFAULTZONE:http://localhost:8761/eureka/}

springdoc:
  swagger-ui:
    urls:
      - name: book-service
        url: /book/v3/api-docs
      - name: exchange-service
        url: /exchange/v3/api-docs
